# Generated by Django 2.0 on 2018-11-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181102_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsbanner',
            options={'verbose_name': '商品轮播图', 'verbose_name_plural': '商品轮播图'},
        ),
    ]
